import banner from './banner/index.js';
import button from './button/index.js';
import card from './card/index.js';
import checkbox from './checkbox/index.js';
import chips from './chips/index.js';
import circularProgress from './circular-progress/index.js';
import dataTable from './data-table/index.js';
import dialog from './dialog/index.js';
import drawer from './drawer/index.js';
import fab from './fab/index.js';
import floatingLabel from './floating-label/index.js';
import iconButton from './icon-button/index.js';
import layoutGrid from './layout-grid/index.js';
import lineRipple from './line-ripple/index.js';
import linearProgress from './linear-progress/index.js';
import list from './list/index.js';
import materialIcon from './material-icon/index.js';
import menu from './menu/index.js';
import notchedOutline from './notched-outline/index.js';
import radio from './radio/index.js';
import segmentedButton from './segmented-button/index.js';
import select from './select/index.js';
import slider from './slider/index.js';
import snackbar from './snackbar/index.js';
import switchControl from './switch/index.js';
import tabs from './tabs/index.js';
import textfield from './textfield/index.js';
import tooltip from './tooltip/index.js';
import topAppBar from './top-app-bar/index.js';

export default {
  install(vm) {
    vm.use(banner);
    vm.use(button);
    vm.use(card);
    vm.use(circularProgress);
    vm.use(checkbox);
    vm.use(chips);
    vm.use(dataTable);
    vm.use(dialog);
    vm.use(drawer);
    vm.use(fab);
    vm.use(floatingLabel);
    vm.use(iconButton);
    vm.use(layoutGrid);
    vm.use(lineRipple);
    vm.use(linearProgress);
    vm.use(list);
    vm.use(materialIcon);
    vm.use(menu);
    vm.use(notchedOutline);
    vm.use(radio);
    vm.use(segmentedButton);
    vm.use(select);
    vm.use(slider);
    vm.use(snackbar);
    vm.use(switchControl);
    vm.use(tabs);
    vm.use(textfield);
    vm.use(tooltip);
    vm.use(topAppBar);
  },
};

export { default as banner } from './banner/index.js';
export * as base from './base/index.js';
export { default as button } from './button/index.js';
export { default as card } from './card/index.js';
export { default as checkbox } from './checkbox/index.js';
export { default as chips } from './chips/index.js';
export { default as circularProgress } from './circular-progress/index.js';
export { default as dataTable } from './data-table/index.js';
export { default as dialog } from './dialog/index.js';
export { default as drawer } from './drawer/index.js';
export { default as fab } from './fab/index.js';
export { default as floatingLabel } from './floating-label/index.js';
export { default as iconButton } from './icon-button/index.js';
export { default as layoutGrid } from './layout-grid/index.js';
export { default as lineRipple } from './line-ripple/index.js';
export { default as linearProgress } from './linear-progress/index.js';
export { default as list } from './list/index.js';
export { default as materialIcon } from './material-icon/index.js';
export { default as menu } from './menu/index.js';
export { default as notchedOutline } from './notched-outline/index.js';
export { default as radio } from './radio/index.js';
export { default as segmentedButton } from './segmented-button/index.js';
export { default as select } from './select/index.js';
export { default as slider } from './slider/index.js';
export { default as snackbar } from './snackbar/index.js';
export { default as switchControl } from './switch/index.js';
export { default as tabs } from './tabs/index.js';
export { default as textfield } from './textfield/index.js';
export { default as tooltip } from './tooltip/index.js';
export { default as topAppBar } from './top-app-bar/index.js';
